
apiVersion: v1
kind: Namespace
metadata:
  name: notes-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  namespace: notes-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: php:7.4-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: notes-svc
  namespace: notes-ns
spec:
  selector:
    app: notes-app
  ports:
    - port: 82
      targetPort: 80
  type: ClusterIP
